{
 "title": "NATS Jetstream Clusters",
 "description": "Jetstream and NATS clusters",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "label": "Region", "query": "prometheus" },
   { "name": "job", "label": "Cluster", "query": { "query": "label_values(job)" } },
   {
    "name": "stream",
    "label": "Stream",
    "query": {
     "query": "label_values(nats_stream_last_seq,stream_name)"
    }
   },
   {
    "name": "consumer",
    "label": "Consumer",
    "query": {
     "query": "label_values(nats_consumer_num_pending,consumer_name)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "query_result(node_namespace_pod:kube_pod_info:{pod=~\"$job-.*\"})"
    }
   }
  ]
 },
 "panels": [
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kube_pod_status_ready{pod=~\"$job-.*\",condition=\"true\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "NATS Msgs Out Rate [5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(nats_varz_out_msgs{pod=~\"$job-.*\"}[5m]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Golchin Consumers on ride-started",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(nats_consumer_delivered_consumer_seq{consumer_name=~\".*golchin.*ride-started.*\"}[5m])) by (consumer_name) and ON() hour() >= 2 <= 23",
     "legendFormat": "{{ consumer_name }} [day]"
    },
    {
     "expr": "sum(rate(nats_consumer_delivered_consumer_seq{consumer_name=~\".*golchin.*ride-started.*\"}[5m])) by (consumer_name) unless on() hour() > 2 < 23",
     "legendFormat": "{{ consumer_name }} [night]"
    }
   ]
  },
  {
   "title": "$stream - Delivered Messages for  Consumers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(nats_consumer_delivered_consumer_seq{pod=~\"$job.*\", stream_name=~\"$stream\"}[5m])) by (stream_name,consumer_name)",
     "legendFormat": "{{stream_name}} - {{consumer_name}}"
    }
   ]
  },
  {
   "title": "$stream - Stream Published",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(nats_stream_last_seq{pod=~\"$job-.*\",stream_name=~\"$stream\"}[5m])",
     "legendFormat": "{{ stream_name }} : {{ stream_leader }} : {{ pod }}"
    }
   ]
  },
  {
   "title": "$job Pod restart",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total{pod=~\"$job-.*\"}[10m])",
     "legendFormat": "{{ pod }} - {{ container }}"
    }
   ]
  },
  {
   "title": "CPU Throttling [2m]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "increase(container_cpu_cfs_throttled_periods_total{pod=~\"$job-.*\", container=\"nats\"}[2m]) / increase(container_cpu_cfs_periods_total{pod=~\"$job-.*\", container=\"nats\"}[2m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Load Avg 5m - $node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "node:load_average:5m{instance=~\"^$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$stream - Consumer Pending Ack",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(nats_consumer_num_ack_pending{stream_name=~\"$stream\",consumer_name=~\"$consumer\",pod=~\"$job.*\"}) by (stream_name,consumer_name)",
     "legendFormat": "{{ stream_name }} - {{ consumer_name }}"
    }
   ]
  },
  { "title": "Nats - Internals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Storage Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nats_varz_jetstream_stats_storage{pod=~\"$job-.*\"})/sum(nats_varz_jetstream_config_max_storage{pod=~\"$job-.*\"})",
     "legendFormat": "{{clusteri_id}}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nats_varz_jetstream_stats_memory{pod=~\"$job-.*\"})/sum(nats_varz_jetstream_config_max_memory{pod=~\"$job-.*\"})"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nats_varz_connections{pod=~\"$job-.*\"})"
    }
   ]
  },
  {
   "title": "Connections per Pod",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nats_varz_connections{pod=~\"$job-.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Slow Consumers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nats_varz_slow_consumers{pod=~\"$job-.*\"}) "
    }
   ]
  },
  {
   "title": "Slow Consumers per Pod",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nats_varz_slow_consumers{pod=~\"$job-.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total Consumers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nats_server_total_consumers{pod=~\"$job-.*\"})"
    }
   ]
  },
  {
   "title": "NATS Bytes In/Out Rate [5m]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(nats_varz_in_bytes{pod=~\"$job.*\"}[5m])",
     "legendFormat": "in - {{ pod }}"
    },
    {
     "expr": "rate(nats_varz_out_bytes{pod=~\"$job.*\"}[5m])",
     "legendFormat": "out - {{pod}}"
    }
   ]
  },
  {
   "title": "NATS Msgs In/Out Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(nats_varz_in_msgs{pod=~\"$job-.*\"}[5m])",
     "legendFormat": "in - {{ pod }}"
    },
    {
     "expr": "rate(nats_varz_out_msgs{pod=~\"$job-.*\"}[5m])",
     "legendFormat": "out - {{ pod }}"
    }
   ]
  },
  {
   "title": "Jetstream Disks Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "cloud:disk_io_throughput:bytes{persistentvolumeclaim=~\"$job.*\"}",
     "legendFormat": "{{ persistentvolumeclaim }}"
    }
   ]
  },
  {
   "title": "Stream Distribution over servers",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nats_server_total_streams{pod=~\"$job.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Jetstream Used Disk",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "nats_varz_jetstream_stats_storage{pod=~\"$job.*\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "NATS Total Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 50 },
   "targets": [
    {
     "expr": "nats_varz_total_connections{pod=~\"$job-.*\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "title": "Streams & Consumers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": " $stream - Stream data size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(nats_stream_total_bytes{stream_name=~\"$stream\",pod=~\"$job.*\"}) by (stream_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " $stream - Stream message count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(nats_stream_total_messages{stream_name=~\"$stream\",pod=~\"$job.*\"}) by (stream_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$stream - Message Rate [5m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum(rate(nats_stream_total_messages{stream_name=~\"$stream\", pod=~\"$job.*\"}[5m])) by (stream_name)",
     "legendFormat": "{{stream_name}}"
    }
   ]
  },
  {
   "title": "$stream - Delivered Messages for  Consumers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "sum(rate(nats_consumer_delivered_consumer_seq{pod=~\"$job.*\", stream_name=~\"$stream\"}[5m])) by (stream_name,consumer_name)",
     "legendFormat": "{{stream_name}} - {{consumer_name}}"
    }
   ]
  },
  {
   "title": "$stream - Stream Published",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(nats_stream_last_seq{pod=~\"$job-.*\",stream_name=~\"$stream\"}[5m])",
     "legendFormat": "{{ stream_name }} : {{ stream_leader }} : {{ pod }}"
    }
   ]
  },
  {
   "title": "$stream - Consumer Re-Delivery [5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(nats_consumer_num_redelivered{pod=~\"$job-.*\", stream_name=~\"$stream\"}[5m]) > 0",
     "legendFormat": "{{ stream_name }} - {{ consumer_name }}"
    }
   ]
  },
  {
   "title": "$stream - Consumer Pending Ack",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(nats_consumer_num_ack_pending{stream_name=~\"$stream\",consumer_name=~\"$consumer\",pod=~\"$job.*\"}) by (stream_name,consumer_name)",
     "legendFormat": "{{ stream_name }} - {{ consumer_name }}"
    }
   ]
  },
  { "title": "Cluster Workload Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "$job Pod Status",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_pod_status_ready{pod=~\"$job-.*\",condition=\"true\"} == 1",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "$job Pod restart",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 82 },
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total{pod=~\"$job-.*\"}[10m])",
     "legendFormat": "{{ pod }} - {{ container }}"
    }
   ]
  },
  {
   "title": "Memory Usage (percent)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 88 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(container_memory_working_set_bytes{pod=~\"$job-.*\"}) by (pod) / sum(container_spec_memory_limit_bytes{pod=~\"$job-.*\"}) by (pod) ) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage (percent)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 88 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{container!=\"POD\", pod=~\"$job-.*\"}[5m])) by (pod)/sum(container_spec_cpu_quota{container!=\"POD\", pod=~\"$job-.*\"} / 100000) by (pod)) * 100 ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage - Nats Container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=~\"$job-.*\",container=\"nats\"}[2m])",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "sum(container_spec_cpu_quota{pod=~\"$job-.*\",container=~\"nats\"}) by(pod) /100000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage - Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
   "targets": [
    {
     "expr": "pod:container_cpu_usage:sum{pod=~\"$job-.*\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{pod=~\"$job-.*\"}[5m])",
     "legendFormat": "receive {{ pod }}"
    },
    {
     "expr": "-rate(container_network_transmit_bytes_total{pod=~\"$job-.*\"}[5m])",
     "legendFormat": "transmit {{ pod }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"$job-.*\"}) by (pod)",
     "legendFormat": "{{pod}} "
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{pod=~\"$job-.*\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Throttling [2m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "increase(container_cpu_cfs_throttled_periods_total{pod=~\"$job-.*\", container=\"nats\"}[2m]) / increase(container_cpu_cfs_periods_total{pod=~\"$job-.*\", container=\"nats\"}[2m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Node Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 } },
  {
   "title": "CPU Usage - $node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "node:cpu_usage:percent{instance=~\"^$node\"}",
     "legendFormat": "Usage ({{node}})"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"^$node\"}[5m]))",
     "legendFormat": "Steal ({{node}})"
    }
   ]
  },
  {
   "title": "Memory Usage - $node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "node:memory_usage:percent{instance=~\"^$node\"}",
     "legendFormat": "Usage ({{instance}})"
    }
   ]
  },
  {
   "title": "Load Avg 5m - $node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 125 },
   "targets": [
    {
     "expr": "node:load_average:5m{instance=~\"^$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Traffic - $node",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "node:net_rx:bps{instance=~\"^$node\"}",
     "legendFormat": "recv {{node}} - {{device}}"
    },
    {
     "expr": "node:net_tx:bps{instance=~\"^$node\"}",
     "legendFormat": "trans {{node}} - {{device}} "
    }
   ]
  }
 ]
}