apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: nats
  namespace: "{{ .Release.Namespace }}"
spec:
  groups:
    - name: nats-custom
      rules:
        - alert: NatsPendingCountExceeded
          expr: 'avg(nats_consumer_num_ack_pending{namespace="<NATS-NAMESPACE>"}) by (stream_name, consumer_name, job) > 1000'
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "stream {{`{{$labels.stream_name}}`}} has unhealthy consumer named {{`{{$labels.consumer_name}}`}} is not healthy ({{`{{$labels.stream_name}}`}})"
            message: "stream {{`{{$labels.stream_name}}`}} has unhealthy consumer named {{`{{$labels.consumer_name}}`}} is not healthy ({{`{{$labels.stream_name}}`}})"
      
        - alert: NatsMemoryPressure
          expr: 'container_memory_working_set_bytes{container!="", namespace="<NATS-NAMESPACE>"}  / (container_spec_memory_limit_bytes{container!="", namespace="<NATS-NAMESPACE>"} != 0) > 0.7'
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Container {{`{{$labels.container}}`}} in Pod {{`{{$labels.pod}}`}} memory is using {{`{{ $value | humanizePercentage }}`}} of its capacity"
            message: "Container {{`{{$labels.container}}`}} in Pod {{`{{$labels.pod}}`}} memory is using {{`{{ $value | humanizePercentage }}`}} of its capacity"
            
        - alert: NatsCPUPressure
          expr: '(sum(rate(container_cpu_usage_seconds_total{namespace="<NATS-NAMESPACE>", container!="POD", pod!=""}[5m])) by (pod)/sum(container_spec_cpu_quota{namespace="<NATS-NAMESPACE>", container!="POD", pod!=""} / 100000) by (pod))  > 0.8'
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Pod {{`{{$labels.pod}}`}} CPU is using {{`{{ $value | humanizePercentage }}`}} of its capacity"
            message: "Pod {{`{{$labels.pod}}`}} CPU is using {{`{{ $value | humanizePercentage }}`}} of its capacity"

        - alert: NatsDiskPressure
          expr: '(sum(kubelet_volume_stats_used_bytes{namespace="<NATS-NAMESPACE>"}) by (persistentvolumeclaim) / sum(kubelet_volume_stats_capacity_bytes{namespace="<NATS-NAMESPACE>"}) by (persistentvolumeclaim)) > 0.8'
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "PVC {{`{{$labels.persistentvolumeclaim}}`}} is using {{`{{ $value | humanizePercentage }}`}} of its capacity."
            message: "PVC {{`{{$labels.persistentvolumeclaim}}`}} is using {{`{{ $value | humanizePercentage }}`}} of its capacity."

        - alert: NatsPodNotReady
          expr: 'kube_pod_container_status_ready{namespace="<NATS-NAMESPACE>"} == 0'
          for: 20s
          labels:
            severity: critical
          annotations:
            summary: "Container {{`{{$labels.container}}`}} in pod {{`{{$labels.namespace}}`}}/{{`{{$labels.pod}}`}} is not ready"
            message: "Container {{`{{$labels.container}}`}} in pod {{`{{$labels.namespace}}`}}/{{`{{$labels.pod}}`}} is not ready"

        - alert: NatsPodRestart
          expr: 'increase(kube_pod_container_status_restarts_total{namespace=~"<NATS-NAMESPACE>"}[20m]) > 2'
          labels:
            severity: critical
          annotations:
            summary: "Pod {{`{{$labels.namespace}}`}}/{{`{{$labels.pod}}`}} has restarted more than 2 times."
            message: "Pod {{`{{$labels.namespace}}`}}/{{`{{$labels.pod}}`}} has restarted more than 2 times in the last 20 minutes."
