---
service:
  loadBalancer:
    enabled: true  # Expose the NATS service using a LoadBalancer

nats:
  global:
    labels:
      app: mynats  # Global label for all NATS components

  natsBox:
    enabled: false  # natsBox for debugging is disabled

  podTemplate:
    patch:
      - op: add
        path: /spec/securityContext
        value:
          sysctls:
            - name: net.core.somaxconn
              value: "16384"  # Optimize OS-level connection backlog queue size

  config:
    cluster:
      noAdvertise: true  # Prevents publishing of cluster routes to clients
      enabled: true  # NATS clustering is enabled
      replicas: 3  # Number of NATS nodes in the cluster
      merge:
        pool_size: 1024  # Custom NATS server pool size configuration

    gateway:
      enabled: false  # NATS Gateway feature is disabled

    jetstream:
      enabled: true  # Enable Jetstream for persistent message storage
      memoryStore:
        enabled: true  # Enable memory storage with a max size
        maxSize: 2Gi  # Max size for the in-memory storage
      fileStore:
        enabled: true  # Enable file storage
        storageDirectory: /data  # Directory for storing the data
        pvc:
          enabled: true  # Enable a PersistentVolumeClaim
          size: 2Gi  # Size of the PVC
          storageClassName: block-storage-high-speed  # Define the storage class for high I/O performance

  container:
    merge:
      resources:
        requests:  # Minimum resources for the NATS container
          cpu: 1
          memory: 1Gi
          ephemeral-storage: 1Gi
        limits:  # Maximum resources for the NATS container
          cpu: 3
          memory: 3Gi
          ephemeral-storage: 1Gi

  promExporter:
    enabled: true  # Enable Prometheus exporter for monitoring
    podMonitor:
      enabled: true  # Enable PodMonitor for Prometheus integration
    merge:
      resources:
        requests:  # Minimum resources for the Prometheus exporter
          cpu: 1
          memory: 500Mi
        limits:  # Maximum resources for the Prometheus exporter
          cpu: 1
          memory: 500Mi

  podDisruptionBudget:
    enabled: false  # Pod disruption budget is not enabled
    maxUnavailable: 1  # Maximum number of unavailable pods during disruption
